### ISSUE TITLE
Doesn't dispatch on the most specific subtype in certain cases

### ISSUE THREAD

**Issue by jsalzbergedu** [gustavcedersjo/multij#7]
I have a type hierarchy that I am trying to dispatch on. For some reason, when I serialize and then de-serialize the object using Jackson, a MultiJ multimethod fails to dispatch on the most specific subtype, but instead dispatches on the first type provided. 

For an example, look at [this file](https://github.com/jsalzbergedu/SrvRequests/blob/master/src/test/java/com/ncsurobotics/srvrequests/TestRequestSenderReceiver.java) on [line 121](https://github.com/jsalzbergedu/SrvRequests/blob/master/src/test/java/com/ncsurobotics/srvrequests/TestRequestSenderReceiver.java#L121). As it is written it works, but if you switch the places of the two `dispatch` definitions in `public interface dispatch`, it stops working. This is quite bizarre given that if you check, the `received` object is indeed of type `ImmutableLifecycleGet`, and `ImmutableLifecycleGet` implements `LifecycleGet` which extends `SrvRequest`, rendering `LifecycleGet` the more specific subtype. Furthermore, the same sort of test worked [here](https://github.com/jsalzbergedu/SrvRequests/blob/master/src/test/java/com/ncsurobotics/srvrequests/TestSrvRequest.java#L129). I don't understand it, and any insight would be greatly appreciated.

Thank you!

**Comment by gustavcedersjo** [comment]
If the wrong method is selected after switching the order in the code, then it sounds like something is not properly recompiled or regenerated. Does the problem persist after a full clean and rebuild of the project?

**Comment by jsalzbergedu** [comment]
Something about the threads and the code generation was messing it up. Just doing a clean and rebuild, or even a clone to a different directory and rebuild, wouldn't do the trick, but changing it to single threaded would. Thanks for the help.
